param(
  [switch]$KeepRunning,
  [switch]$ResetLocal
)
$ErrorActionPreference='Stop'
$root=Split-Path -Parent $PSScriptRoot
Set-Location $root
function Pass($m){Write-Host "PASS $m"}
function Assert($c,$m){if(!$c){throw $m};Pass $m}
function Native($m){Assert ($LASTEXITCODE-eq0) "$m exit"}
function HttpStatus($uri,$method,$headers,$body){try{$r=Invoke-WebRequest $uri -Method $method -Headers $headers -ContentType application/json -Body $body -UseBasicParsing;[int]$r.StatusCode}catch{if($_.Exception.Response){[int]$_.Exception.Response.StatusCode}else{throw}}}
function ChunkedStatus($uri,$headers,$body){$r=[Net.HttpWebRequest]::Create($uri);$r.Method='POST';$r.ContentType='application/json';$r.SendChunked=$true;foreach($h in $headers.GetEnumerator()){$r.Headers.Add($h.Key,$h.Value)};$b=[Text.Encoding]::UTF8.GetBytes($body);$s=$r.GetRequestStream();try{$s.Write($b,0,$b.Length)}finally{$s.Dispose()};try{$x=$r.GetResponse();try{[int]$x.StatusCode}finally{$x.Dispose()}}catch [Net.WebException]{if($_.Exception.Response){$x=$_.Exception.Response;try{[int]$x.StatusCode}finally{$x.Dispose()}}else{throw}}}
function MetaHeaders($body,$secret){$h=[Security.Cryptography.HMACSHA256]::new([Text.Encoding]::UTF8.GetBytes($secret));try{$digest=($h.ComputeHash([Text.Encoding]::UTF8.GetBytes($body))|% ToString x2)-join''}finally{$h.Dispose()};@{'x-hub-signature-256'="sha256=$digest"}}
$generated=Join-Path $root '.generated'
$localEnvFile=Join-Path $root '.env'
$envFile=Join-Path $generated 'runtime.env'
$failure=$null;$cleanupFailure=$null;$managedEnvironment=$false;$lockAcquired=$false
$mutex=[Threading.Mutex]::new($false,'Local\N8NSalesFlowAIHarness')
try {
  # ponytail: one lock per Windows login session; use a checkout-scoped mutex if parallel clones matter.
  $lockAcquired=$mutex.WaitOne(0);if(-not$lockAcquired){throw 'Another SalesFlow harness is already running.'}
  if($ResetLocal-and-not$KeepRunning){throw '-ResetLocal requires -KeepRunning.'}
  docker info *> $null;Native 'Docker readiness'
  $composeProject=(docker compose --env-file .env.example config --format json|ConvertFrom-Json).name;Native 'compose project resolution'
  $existingVolumes=@(docker volume ls --filter "label=com.docker.compose.project=$composeProject" -q);Native 'local volume inventory'
  $localEnvExists=Test-Path $localEnvFile
  if(($localEnvExists-or$existingVolumes)-and-not$ResetLocal){$recovery=if($localEnvExists-and$existingVolumes){'Resume with docker compose --env-file .env up -d'}else{'The local environment is incomplete'};throw "$recovery. Replace it explicitly with -KeepRunning -ResetLocal."}
  $manifest=Get-Content release/release-manifest.json -Raw|ConvertFrom-Json
  $composeText=Get-Content compose.yaml -Raw;Assert (-not$manifest.livePromotionAllowed-and$composeText-match'N8N_BLOCK_ENV_ACCESS_IN_NODE:\s*"false"') 'env-readable local topology cannot be promoted'
  $workflows=@(Get-ChildItem workflows -Filter *.json|Sort-Object Name);Assert ($workflows.Count-eq7) 'seven workflows'
  $configs=@(Get-ChildItem config -Filter *.json|Sort-Object Name);Assert ((Compare-Object @($configs.Name) @($manifest.configFiles)).Count-eq0) 'exact config file set'
  Assert ((Compare-Object @($workflows.Name) @($manifest.workflowFiles)).Count-eq0) 'exact workflow file set'
  $releaseSet=Get-Content config/release-set.json -Raw|ConvertFrom-Json;Assert ($releaseSet.reviewedManifestHash-eq$manifest.activationManifestSha256-and$releaseSet.manifestVersion-eq$manifest.activationManifest.version-and$releaseSet.policyVersion-eq$manifest.activationManifest.policyVersion-and$releaseSet.knowledgeVersion-eq$manifest.activationManifest.knowledgeVersion) 'exact activation manifest binding';foreach($p in $manifest.activationManifest.inputHashes.psobject.Properties){Assert ($manifest.inputHashes.($p.Name)-eq$p.Value) "activation input $($p.Name)"}
  $types=@();foreach($f in $workflows){$w=Get-Content $f.FullName -Raw|ConvertFrom-Json;$types+=$w.nodes.type;Assert ($w.settings.saveDataSuccessExecution-eq'none'-and$w.settings.saveDataErrorExecution-eq'none'-and!$w.settings.saveManualExecutions) "$($f.Name) persistence disabled"}
  Assert ((Compare-Object @($types|Sort-Object -Unique) @($manifest.nodeTypes)).Count-eq0) 'approved native nodes exact'
  $w5=Get-Content workflows/05-follow-up-scheduler.json -Raw;Assert ($w5-match'scheduleTrigger'-and$w5-match'schedule_work'-and$w5-match'salesflow-wf-03'-and$w5-match'salesflow-wf-06') 'UTC scheduler chains durable workers'
  Assert (-not((Get-Content workflows/03-outbox-dispatcher.json,workflows/06-handoff-dispatcher.json -Raw)-match'body\.outcome')) 'internal adapter outcomes'
  foreach($p in $manifest.inputHashes.psobject.Properties){Assert ((Get-FileHash $p.Name -Algorithm SHA256).Hash.ToLower()-eq$p.Value) "manifest input $($p.Name)"}
  $signatures=rg -o "CREATE OR REPLACE FUNCTION [^(]+\([^)]*\)" database/001-initial.sql;Native 'function signature scan';Assert (-not($signatures|Group-Object|Where-Object Count -gt 1)) 'one definition per public function signature'
  $ids=(Get-Content tests/pilot-scenarios.json -Raw|ConvertFrom-Json).scenarios;$sql=Get-Content tests/runtime.sql -Raw
  foreach($id in $ids){Assert ($sql-match"INSERT INTO evidence[^;]*\('$id'\)") "$id asserted before marker"}
  if($ResetLocal){
    $oldEnvFile=if($localEnvExists){$localEnvFile}else{Join-Path $root '.env.example'}
    $ErrorActionPreference='Continue'
    docker compose --env-file $oldEnvFile down -v --remove-orphans *> $null;Native 'existing local reset'
    $remaining=@(docker volume ls --filter "label=com.docker.compose.project=$composeProject" -q);Native 'reset volume inventory';Assert (-not$remaining) 'existing local volumes removed'
    Remove-Item $localEnvFile -Force -ErrorAction SilentlyContinue
    $ErrorActionPreference='Stop'
  }
  $managedEnvironment=$true
  Remove-Item $generated -Recurse -Force -ErrorAction SilentlyContinue;New-Item $generated -ItemType Directory|Out-Null;New-Item (Join-Path $generated exported) -ItemType Directory|Out-Null
  $scheduler=[guid]::NewGuid().ToString('N')+[guid]::NewGuid().ToString('N');$encryption=[guid]::NewGuid().ToString('N')+[guid]::NewGuid().ToString('N');$super=[guid]::NewGuid().ToString('N');$owner=[guid]::NewGuid().ToString('N');$n8ndb=[guid]::NewGuid().ToString('N');$workflowdb=[guid]::NewGuid().ToString('N');$metaRuntime=[guid]::NewGuid().ToString('N')+[guid]::NewGuid().ToString('N');$metaSecret=[guid]::NewGuid().ToString('N')+[guid]::NewGuid().ToString('N');$metaVerify=[guid]::NewGuid().ToString('N')
  $envText=(Get-Content .env.example -Raw)-replace'(?m)^SCHEDULER_TOKEN=.*$',"SCHEDULER_TOKEN=$scheduler"-replace'(?m)^N8N_ENCRYPTION_KEY=.*$',"N8N_ENCRYPTION_KEY=$encryption"-replace'(?m)^POSTGRES_SUPERUSER_PASSWORD=.*$',"POSTGRES_SUPERUSER_PASSWORD=$super"-replace'(?m)^MIGRATION_PASSWORD=.*$',"MIGRATION_PASSWORD=$owner"-replace'(?m)^N8N_DB_PASSWORD=.*$',"N8N_DB_PASSWORD=$n8ndb"-replace'(?m)^WORKFLOW_DB_PASSWORD=.*$',"WORKFLOW_DB_PASSWORD=$workflowdb"-replace'(?m)^META_ACCOUNT_REF=.*$',"META_ACCOUNT_REF=test-account"-replace'(?m)^META_WABA_ID=.*$',"META_WABA_ID=test-waba"-replace'(?m)^META_PHONE_NUMBER_ID=.*$',"META_PHONE_NUMBER_ID=test-phone"-replace'(?m)^META_VERIFY_TOKEN=.*$',"META_VERIFY_TOKEN=$metaVerify"-replace'(?m)^META_RUNTIME_TOKEN=.*$',"META_RUNTIME_TOKEN=$metaRuntime"
  [IO.File]::WriteAllText($envFile,$envText,[Text.UTF8Encoding]::new($false))
  $ErrorActionPreference='Continue'
  docker compose --env-file $envFile down -v --remove-orphans *> $null;Native 'initial cleanup'
  docker compose --env-file $envFile up -d postgres --wait *> $null;Native 'postgres readiness'
  $migration=(Get-Content database/001-initial.sql -Raw)-replace'__MIGRATION_PASSWORD__',$owner-replace'__WORKFLOW_DB_PASSWORD__',$workflowdb-replace'__N8N_DB_PASSWORD__',$n8ndb
  "CREATE DATABASE salesflow_legacy;"|docker compose --env-file $envFile exec -T postgres psql -U postgres -d postgres -v ON_ERROR_STOP=1 *> $null;Native 'legacy database create'
  @"
CREATE ROLE salesflow_owner LOGIN PASSWORD '$owner' NOINHERIT;
CREATE EXTENSION pgcrypto;
CREATE SCHEMA salesflow AUTHORIZATION salesflow_owner;
SET ROLE salesflow_owner;
SET search_path=salesflow,public;
CREATE TABLE accounts(id text PRIMARY KEY,enabled bool NOT NULL DEFAULT true);
CREATE TABLE contacts(account_ref text NOT NULL REFERENCES accounts(id),id uuid NOT NULL DEFAULT gen_random_uuid(),external_ref text NOT NULL,locale text NOT NULL DEFAULT'en',PRIMARY KEY(account_ref,id),UNIQUE(account_ref,external_ref));
CREATE TABLE conversations(account_ref text NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),contact_id uuid NOT NULL,lifecycle text NOT NULL DEFAULT'active',owner text NOT NULL DEFAULT'ai',version bigint NOT NULL DEFAULT 0,last_seq bigint NOT NULL DEFAULT 0,campaign bool NOT NULL DEFAULT true,PRIMARY KEY(account_ref,id),UNIQUE(account_ref,contact_id),FOREIGN KEY(account_ref,contact_id)REFERENCES contacts(account_ref,id));
CREATE TABLE inbound_messages(account_ref text NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),conversation_id uuid NOT NULL,provider_id text NOT NULL,contact_ref text NOT NULL,body text NOT NULL,body_hash text NOT NULL,received_at timestamptz NOT NULL,seq bigint NOT NULL,PRIMARY KEY(account_ref,id),UNIQUE(account_ref,provider_id),UNIQUE(account_ref,conversation_id,seq),FOREIGN KEY(account_ref,conversation_id)REFERENCES conversations(account_ref,id));
INSERT INTO accounts VALUES('legacy-account',true);
INSERT INTO contacts(account_ref,id,external_ref)VALUES('legacy-account','11111111-1111-4111-8111-111111111111','deleted-legitimate-number'),('legacy-account','22222222-2222-4222-8222-222222222222','deleted-22222222-2222-4222-8222-222222222222');
INSERT INTO conversations(account_ref,id,contact_id,last_seq)VALUES('legacy-account','33333333-3333-4333-8333-333333333333','11111111-1111-4111-8111-111111111111',1);
INSERT INTO inbound_messages(account_ref,id,conversation_id,provider_id,contact_ref,body,body_hash,received_at,seq)VALUES('legacy-account','44444444-4444-4444-8444-444444444444','33333333-3333-4333-8333-333333333333','legacy-provider','deleted-legitimate-number','legacy body',encode(digest('legacy body','sha256'),'hex'),now(),1);
"@|docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow_legacy -v ON_ERROR_STOP=1 *> $null;Native 'legacy database seed'
  $legacyMigration=$migration-replace'DATABASE salesflow','DATABASE salesflow_legacy'
  1..2|%{$legacyMigration|docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow_legacy -v ON_ERROR_STOP=1 *> $null;Native "legacy migration $_"}
  $legacyResult=docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow_legacy -Atc "SELECT count(*)||':'||(SELECT count(*)FROM salesflow.contact_identifiers WHERE(account_ref,contact_id,external_ref)=('legacy-account','11111111-1111-4111-8111-111111111111','deleted-legitimate-number')AND active)||':'||(SELECT count(*)FROM salesflow.contact_identifiers WHERE contact_id='22222222-2222-4222-8222-222222222222')||':'||(SELECT count(*)FROM salesflow.conversations WHERE(account_ref,id,contact_id)=('legacy-account','33333333-3333-4333-8333-333333333333','11111111-1111-4111-8111-111111111111'))||':'||(SELECT count(*)FROM salesflow.inbound_messages WHERE(account_ref,id,conversation_id,seq)=('legacy-account','44444444-4444-4444-8444-444444444444','33333333-3333-4333-8333-333333333333',1))||':'||(SELECT count(*)FROM information_schema.columns WHERE table_schema='salesflow'AND table_name='contacts'AND column_name='external_ref')FROM salesflow.contacts WHERE account_ref='legacy-account'";Native 'legacy upgrade evidence query';Assert ($legacyResult.Trim()-eq'2:1:0:1:1:0') 'legacy UUID, history, exact sentinel, and identifier backfill preserved'
  "DROP DATABASE salesflow_legacy WITH (FORCE);CREATE DATABASE salesflow_atomic;"|docker compose --env-file $envFile exec -T postgres psql -U postgres -d postgres -v ON_ERROR_STOP=1 *> $null;Native 'atomic database create'
  $atomicMigration=($migration-replace'DATABASE salesflow','DATABASE salesflow_atomic')-replace'RESET ROLE;','SELECT 1/0;RESET ROLE;'
  $atomicMigration|docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow_atomic -v ON_ERROR_STOP=1 *> $null
  Assert ($LASTEXITCODE-ne0) 'atomic failure fixture fails'
  $atomicResult=docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow_atomic -Atc "SELECT to_regnamespace('salesflow')IS NULL";Native 'atomic rollback evidence query';Assert ($atomicResult.Trim()-eq't') 'failed migration leaves no partial schema'
  "DROP DATABASE salesflow_atomic WITH (FORCE);"|docker compose --env-file $envFile exec -T postgres psql -U postgres -d postgres -v ON_ERROR_STOP=1 *> $null;Native 'migration fixture cleanup'
  1..2|%{$migration|docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -v ON_ERROR_STOP=1 *> $null;Native "migration $_"}
  $rt=[guid]::NewGuid().ToString('N')+[guid]::NewGuid().ToString('N');$rt2=[guid]::NewGuid().ToString('N')+[guid]::NewGuid().ToString('N');$op=[guid]::NewGuid().ToString('N')+[guid]::NewGuid().ToString('N');$op2=[guid]::NewGuid().ToString('N')+[guid]::NewGuid().ToString('N')
  $account=Get-Content config/account.json -Raw|ConvertFrom-Json;Assert ($account.accountRef-eq'test-account') 'account config drives fixture';$accountEnabled=if($account.enabled){'true'}else{'false'}
  @"
SET search_path=salesflow,public;INSERT INTO accounts VALUES('$($account.accountRef)',$accountEnabled),('account-b',true);
SELECT bootstrap('$rt','runtime','runtime-a','test-account');SELECT bootstrap('$rt2','runtime','runtime-b','account-b');SELECT bootstrap('$metaRuntime','runtime','meta-runtime','test-account');SELECT bootstrap('$op','operator','operator-a','test-account');SELECT bootstrap('$op2','operator','operator-b','account-b');SELECT bootstrap('$scheduler','scheduler','scheduler',NULL);
INSERT INTO controls VALUES('test-account','stop','{"enabled":false}'),('account-b','stop','{"enabled":false}');
"@|docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -v ON_ERROR_STOP=1 *> $null;Native 'account bootstrap'
  function ConfigJson($query,$label){$out=$query|docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -v ON_ERROR_STOP=1 -qAt;Native "$label query";$r=$out|ConvertFrom-Json;Assert ($null-ne$r-and$r.ok) "$label ok";$r}
  $priorReleaseJson='{"accountRef":"test-account","kind":"release_set","version":"release-v4","reviewedManifestHash":"364382d5add4c6c84f60076231d102dff7c5ff8fb7cab2462fb034725497f517","policyVersion":"policy-v1","knowledgeVersion":"knowledge-v1","manifestVersion":"release-v4"}';$r=ConfigJson "SELECT salesflow.save_config('$op','$priorReleaseJson'::jsonb);" 'save existing release v4';Assert $r.created 'release v4 fixture created';$r=ConfigJson "SELECT salesflow.activate_config('$op','test-account','release_set','release-v4',NULL);" 'activate existing release v4';Assert $r.activated 'release v4 fixture activated'
  foreach($f in Get-ChildItem config -Filter *.json|? Name -ne account.json){$j=Get-Content $f.FullName -Raw;$q=$j-replace"'","''";$b=$j|ConvertFrom-Json;$r=ConfigJson "SELECT salesflow.save_config('$op','$q');" "save $($f.Name) a";Assert $r.created "$($f.Name) a created";$expected=if($b.kind-eq'release_set'){"'release-v4'"}else{'NULL'};$r=ConfigJson "SELECT salesflow.activate_config('$op','$($b.accountRef)','$($b.kind)','$($b.version)',$expected);" "activate $($f.Name) a";Assert $r.activated "$($f.Name) a activated";$b.accountRef='account-b';$q=(($b|ConvertTo-Json -Compress -Depth 20)-replace"'","''");$r=ConfigJson "SELECT salesflow.save_config('$op2','$q');" "save $($f.Name) b";Assert $r.created "$($f.Name) b created";$r=ConfigJson "SELECT salesflow.activate_config('$op2','account-b','$($b.kind)','$($b.version)',NULL);" "activate $($f.Name) b";Assert $r.activated "$($f.Name) b activated"}
  $releaseUpgrade=docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -Atc "SELECT count(*)||':'||max(version)FILTER(WHERE active)FROM salesflow.config_docs WHERE account_ref='test-account'AND kind='release_set'";Native 'release upgrade query';Assert ($releaseUpgrade.Trim()-eq'2:release-v5') 'release set upgrades v4 to active v5'
  $priv=docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -Atc "SELECT has_table_privilege('salesflow_runtime','salesflow.auth_tokens','INSERT')||':'||has_table_privilege('salesflow_runtime','salesflow.audit_events','UPDATE')";Native 'privilege query';Assert ($priv.Trim()-eq'false:false') 'least privilege runtime'
  $priv=docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -Atc "SELECT has_function_privilege('salesflow_runtime','salesflow.ingest_core(text,jsonb,boolean)','EXECUTE')::text";Native 'ingest core privilege query';Assert ($priv.Trim()-eq'false') 'runtime cannot execute private ingest core'
  $activationJson=$manifest.activationManifest|ConvertTo-Json -Compress -Depth 30;$activationB64=[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($activationJson));$activationHash=$manifest.activationManifestSha256;Get-Content tests/runtime.sql -Raw|docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -v ON_ERROR_STOP=1 -v runtime_token=$rt -v runtime_token_2=$rt2 -v operator_token=$op -v scheduler_token=$scheduler -v activation_manifest_b64=$activationB64 -v activation_manifest_hash=$activationHash > (Join-Path $generated runtime.txt);Native 'runtime SQL'
  $line=Get-Content (Join-Path $generated runtime.txt)|?{$_-like'SCENARIOS=*'}|Select-Object -Last 1;Assert ((Compare-Object @($ids|Sort-Object) @(($line-replace'^SCENARIOS=','')-split','|Sort-Object)).Count-eq0) 'S01-S26 exact'
  $jobScript={param($cwd,$ef,$query)Set-Location $cwd;$out=$query|docker compose --env-file $ef exec -T postgres psql -U postgres -d salesflow -v ON_ERROR_STOP=1 -qAt 2>&1;if($LASTEXITCODE-ne0){throw "native psql failed: $out"};$out}
  function Race($queries,$label){$jobs=@($queries|%{Start-Job -ScriptBlock $jobScript -ArgumentList $root,$envFile,$_});$jobs|Wait-Job|Out-Null;foreach($j in $jobs){Assert ($j.State-eq'Completed') "$label worker native exit"};$jobs|Receive-Job|Out-Null;$jobs|Remove-Job}
  Race @(1..6|%{"SET search_path=salesflow,public;SELECT ingest('$rt',jsonb_build_object('account_ref','test-account','provider_id','parallel-replay','contact_ref','parallel','body','hello'));"}) 'replay'
  $n=docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -Atc "SELECT count(*) FROM salesflow.inbound_messages WHERE provider_id='parallel-replay'";Native 'replay count';Assert ($n.Trim()-eq'1') 'parallel replay one row'
  Race @(1..6|%{$body=if($_%2){'one'}else{'two'};"SET search_path=salesflow,public;SELECT ingest('$rt',jsonb_build_object('account_ref','test-account','provider_id','parallel-conflict','contact_ref','parallel-conflict','body','$body'));"}) 'conflicting replay'
  $n=docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -Atc "SELECT count(*) FROM salesflow.inbound_messages WHERE provider_id='parallel-conflict'";Native 'conflicting replay count';Assert ($n.Trim()-eq'1') 'conflicting replay one row'
  $out="SET search_path=salesflow,public;SELECT ingest('$rt',jsonb_build_object('account_ref','test-account','provider_id','parallel-conflict','contact_ref','parallel-conflict','body',CASE WHEN(SELECT body FROM salesflow.inbound_messages WHERE provider_id='parallel-conflict')='one'THEN'two'ELSE'one'END))->>'reason';"|docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -At;Native 'conflicting replay verdict';Assert ($out.Trim()-eq'idempotency_conflict') 'conflicting replay rejected'
  Race @(1..6|%{"SET search_path=salesflow,public;SELECT ingest('$rt',jsonb_build_object('account_ref','test-account','provider_id','parallel-seq-$_','contact_ref','parallel-seq','body','hello'));"}) 'sequence'
  $n=docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -Atc "SELECT count(*)||':'||count(DISTINCT seq)||':'||min(seq)||':'||max(seq)FROM salesflow.inbound_messages WHERE provider_id LIKE'parallel-seq-%'";Native 'sequence count';Assert ($n.Trim()-eq'6:6:1:6') 'parallel sequence unique and consecutive'
  $replaceSeed=ConfigJson "SELECT salesflow.ingest('$rt',jsonb_build_object('account_ref','test-account','provider_id','replace-race-seed','contact_ref','replace-race-old','body','hello'));" 'replacement race seed';$replaceContact=$replaceSeed.contact_id
  @"
SET search_path=salesflow,public;
CREATE OR REPLACE FUNCTION pause_identifier_replacement_fixture()RETURNS trigger LANGUAGE plpgsql AS `$`$BEGIN IF NEW.event='contact_identifier_replaced'AND NEW.details->>'contact_id'='$replaceContact'THEN PERFORM pg_sleep(2);END IF;RETURN NEW;END`$`$;
CREATE TRIGGER pause_identifier_replacement_fixture BEFORE INSERT ON audit_events FOR EACH ROW EXECUTE FUNCTION pause_identifier_replacement_fixture();
"@|docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -v ON_ERROR_STOP=1 *> $null;Native 'replacement race pause fixture'
  $replaceJob=Start-Job -ScriptBlock $jobScript -ArgumentList $root,$envFile,"SET search_path=salesflow,public;SELECT replace_contact_identifier('$op','test-account','$replaceContact','whatsapp','meta','replace-race-old','replace-race-new');";$paused=$false;for($i=0;$i-lt20;$i++){$n=docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -Atc "SELECT EXISTS(SELECT 1 FROM pg_stat_activity WHERE datname='salesflow'AND query LIKE'%replace-race-old%'AND wait_event='PgSleep')";Native 'replacement pause poll';if($n.Trim()-eq't'){$paused=$true;break};Start-Sleep -Milliseconds 100};Assert $paused 'replacement pauses after new identifier insert';$ingressJob=Start-Job -ScriptBlock $jobScript -ArgumentList $root,$envFile,"SET search_path=salesflow,public;SELECT ingest('$rt',jsonb_build_object('account_ref','test-account','provider_id','replace-race-inbound','contact_ref','replace-race-new','body','during replacement'));";$jobs=@($replaceJob,$ingressJob);$jobs|Wait-Job|Out-Null;foreach($j in $jobs){Assert ($j.State-eq'Completed') 'replacement ingress race worker native exit'};$raceJson=@($jobs|Receive-Job|?{$_-match'^\{'}|%{$_|ConvertFrom-Json});$jobs|Remove-Job;"SET search_path=salesflow,public;DROP TRIGGER pause_identifier_replacement_fixture ON audit_events;DROP FUNCTION pause_identifier_replacement_fixture();"|docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -v ON_ERROR_STOP=1 *> $null;Native 'replacement race pause cleanup';$ingressRace=@($raceJson|?{$_.accepted-eq$true});Assert ($ingressRace.Count-eq1-and$ingressRace[0].created-and$ingressRace[0].contact_id-eq$replaceContact) 'ingress through concurrently replaced reference resolves stable Contact'
  $replaceDeleteSeed=ConfigJson "SELECT salesflow.ingest('$rt',jsonb_build_object('account_ref','test-account','provider_id','replace-delete-seed','contact_ref','replace-delete-old','body','hello'));" 'replacement deletion race seed';$replaceDeleteContact=$replaceDeleteSeed.contact_id
  @"
SET search_path=salesflow,public;
CREATE OR REPLACE FUNCTION pause_identifier_replacement_fixture()RETURNS trigger LANGUAGE plpgsql AS `$`$BEGIN IF NEW.event='contact_identifier_replaced'AND NEW.details->>'contact_id'='$replaceDeleteContact'THEN PERFORM pg_sleep(2);END IF;RETURN NEW;END`$`$;
CREATE TRIGGER pause_identifier_replacement_fixture BEFORE INSERT ON audit_events FOR EACH ROW EXECUTE FUNCTION pause_identifier_replacement_fixture();
"@|docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -v ON_ERROR_STOP=1 *> $null;Native 'replacement deletion pause fixture';$replaceJob=Start-Job -ScriptBlock $jobScript -ArgumentList $root,$envFile,"SET search_path=salesflow,public;SELECT replace_contact_identifier('$op','test-account','$replaceDeleteContact','whatsapp','meta','replace-delete-old','replace-delete-new');";$paused=$false;for($i=0;$i-lt20;$i++){$n=docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -Atc "SELECT EXISTS(SELECT 1 FROM pg_stat_activity WHERE datname='salesflow'AND query LIKE'%replace-delete-old%'AND wait_event='PgSleep')";Native 'replacement deletion pause poll';if($n.Trim()-eq't'){$paused=$true;break};Start-Sleep -Milliseconds 100};Assert $paused 'replacement deletion pauses after new identifier insert';$deleteJob=Start-Job -ScriptBlock $jobScript -ArgumentList $root,$envFile,"SET search_path=salesflow,public;SELECT operations('$op','test-account',jsonb_build_object('action','delete','contact_id','$replaceDeleteContact'));";$jobs=@($replaceJob,$deleteJob);$jobs|Wait-Job|Out-Null;foreach($j in $jobs){Assert ($j.State-eq'Completed') 'replacement deletion race worker native exit'};$jobs|Receive-Job|Out-Null;$jobs|Remove-Job;"SET search_path=salesflow,public;DROP TRIGGER pause_identifier_replacement_fixture ON audit_events;DROP FUNCTION pause_identifier_replacement_fixture();"|docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -v ON_ERROR_STOP=1 *> $null;Native 'replacement deletion pause cleanup';$n=docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -Atc "SELECT count(*)||':'||count(*)FILTER(WHERE NOT active AND retired_at IS NOT NULL)||':'||(SELECT count(*)FROM salesflow.deletion_targets dt JOIN salesflow.deletion_requests dr ON(dr.account_ref,dr.id)=(dt.account_ref,dt.request_id)WHERE(dt.account_ref,dr.contact_id,dt.target_type)=('test-account','$replaceDeleteContact','contact_identifier'))FROM salesflow.contact_identifiers WHERE(account_ref,contact_id)=('test-account','$replaceDeleteContact')";Native 'replacement deletion race evidence';Assert ($n.Trim()-eq'2:2:2') 'deletion serializes after replacement and tracks every identifier'
  $deleteSeed=ConfigJson "SELECT salesflow.ingest('$rt',jsonb_build_object('account_ref','test-account','provider_id','delete-race-seed','contact_ref','delete-race-ref','body','seed'));" 'deletion race seed';$deleteContact=$deleteSeed.contact_id;$deleteConversation=$deleteSeed.conversation_id;$blockJob=Start-Job -ScriptBlock $jobScript -ArgumentList $root,$envFile,"SET search_path=salesflow,public;BEGIN;SELECT id FROM conversations WHERE(account_ref,id)=('test-account','$deleteConversation')FOR UPDATE;SELECT pg_advisory_xact_lock(hashtextextended('test-account:delete-race-ready',0));SELECT pg_sleep(4);COMMIT;";$blocked=$false;for($i=0;$i-lt20;$i++){$n=docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -Atc "SELECT NOT pg_try_advisory_xact_lock(hashtextextended('test-account:delete-race-ready',0))";Native 'deletion race blocker poll';if($n.Trim()-eq't'){$blocked=$true;break};Start-Sleep -Milliseconds 100};Assert $blocked 'deletion race Conversation blocker held';$lateIngress=Start-Job -ScriptBlock $jobScript -ArgumentList $root,$envFile,"SET search_path=salesflow,public;SELECT ingest('$rt',jsonb_build_object('account_ref','test-account','provider_id','delete-race-late','contact_ref','delete-race-ref','body','late plaintext'));";$identityLocked=$false;for($i=0;$i-lt20;$i++){$n=docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -Atc "SELECT NOT pg_try_advisory_xact_lock(hashtextextended('test-account:whatsapp:meta:'||encode(digest('delete-race-ref','sha256'),'hex'),0))";Native 'deletion race identity poll';if($n.Trim()-eq't'){$identityLocked=$true;break};Start-Sleep -Milliseconds 100};Assert $identityLocked 'late ingress resolved identifier before deletion';$deleteJob=Start-Job -ScriptBlock $jobScript -ArgumentList $root,$envFile,"SET search_path=salesflow,public;SELECT operations('$op','test-account',jsonb_build_object('action','delete','contact_id','$deleteContact'));";$jobs=@($blockJob,$lateIngress,$deleteJob);$jobs|Wait-Job|Out-Null;foreach($j in $jobs){Assert ($j.State-eq'Completed') 'deletion ingress race worker native exit'};$jobs|Receive-Job|Out-Null;$jobs|Remove-Job;$n=docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -Atc "SELECT count(*)||':'||count(*)FILTER(WHERE body='[deleted]'AND contact_ref='[deleted]')||':'||(SELECT count(*)FROM salesflow.deletion_targets dt JOIN salesflow.deletion_requests dr ON(dr.account_ref,dr.id)=(dt.account_ref,dt.request_id)WHERE(dt.account_ref,dr.contact_id,dt.target_type,dt.target_id)=('test-account','$deleteContact','inbound_message',(SELECT id::text FROM salesflow.inbound_messages WHERE provider_id='delete-race-late')))FROM salesflow.inbound_messages WHERE provider_id IN('delete-race-seed','delete-race-late')";Native 'deletion ingress race evidence';Assert ($n.Trim()-eq'2:2:1') 'deletion waits for ingress and minimizes the late message'
  $raceA='{"accountRef":"test-account","kind":"qualification","version":"qualification-race-a","minimumScore":1,"handoffScore":5}';$raceB='{"accountRef":"test-account","kind":"qualification","version":"qualification-race-b","minimumScore":1,"handoffScore":5}';$r=ConfigJson "SELECT salesflow.save_config('$op','$raceA');" 'save activation race a';Assert $r.created 'activation race a created';$r=ConfigJson "SELECT salesflow.save_config('$op','$raceB');" 'save activation race b';Assert $r.created 'activation race b created';$lockQuery="BEGIN;SELECT pg_advisory_xact_lock(hashtextextended('test-account:qualification',0));SELECT pg_sleep(2);SELECT salesflow.activate_config('$op','test-account','qualification','qualification-race-a','qualification-v1');COMMIT;";$lockJob=Start-Job -ScriptBlock $jobScript -ArgumentList $root,$envFile,$lockQuery;$locked=$false;for($i=0;$i-lt20;$i++){$n=docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -Atc "SELECT NOT pg_try_advisory_xact_lock(hashtextextended('test-account:qualification',0))";Native 'activation lock poll';if($n.Trim()-eq't'){$locked=$true;break};Start-Sleep -Milliseconds 100};Assert $locked 'activation race exact lock held';$contender=Start-Job -ScriptBlock $jobScript -ArgumentList $root,$envFile,"SELECT salesflow.activate_config('$op','test-account','qualification','qualification-race-b','qualification-v1');";$jobs=@($lockJob,$contender);$jobs|Wait-Job|Out-Null;foreach($j in $jobs){Assert ($j.State-eq'Completed') 'config activation worker native exit'};$raceJson=@($jobs|Receive-Job|?{$_-match'^\{'}|%{$_|ConvertFrom-Json});$jobs|Remove-Job;$losers=@($raceJson|?{$_.reason-in@('busy','stale_active_version')});Assert (@($raceJson|? ok).Count-eq1-and$losers.Count-eq1) 'activation contention returns one winner and one bounded denial';$n=docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -Atc "SELECT count(*)||':'||(SELECT count(*)FROM salesflow.audit_events WHERE account_ref='test-account'AND event='config_activated'AND details->>'targetVersion'LIKE'qualification-race-%')FROM salesflow.config_docs WHERE account_ref='test-account'AND kind='qualification'AND active AND version LIKE'qualification-race-%'";Native 'activation race evidence';Assert ($n.Trim()-eq'1:1') 'activation race one active and one audit';$active=docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -Atc "SELECT version FROM salesflow.config_docs WHERE account_ref='test-account'AND kind='qualification'AND active";Native 'activation race winner query';$r=ConfigJson "SELECT salesflow.activate_config('$op','test-account','qualification','qualification-v1','$($active.Trim())');" 'activation race rollback';Assert $r.activated 'activation race rolled back'
  $credential=ConvertTo-Json -InputObject @(@{id='salesflow-postgres-local';name='SalesFlow PostgreSQL';type='postgres';data=@{host='postgres';database='salesflow';user='salesflow_runtime';password=$workflowdb;port=5432;ssl='disable'}},@{id='salesflow-meta-hmac-local';name='SalesFlow Meta HMAC';type='crypto';data=@{hmacSecret=$metaSecret}}) -Depth 6
  [IO.File]::WriteAllText((Join-Path $generated credentials.json),$credential,[Text.UTF8Encoding]::new($false))
  docker compose --env-file $envFile up -d n8n *> $null;Native 'n8n start'
  $ready=$false;for($i=0;$i-lt60;$i++){try{$null=Invoke-WebRequest http://127.0.0.1:5678/healthz -UseBasicParsing -TimeoutSec 2;$ready=$true;break}catch{Start-Sleep 2}};Assert $ready 'bounded n8n readiness'
  docker compose --env-file $envFile exec -T n8n n8n import:credentials --input=/generated/credentials.json *> $null;Native 'credential import'
  docker compose --env-file $envFile exec -T n8n n8n import:workflow --separate --input=/repo/workflows *> $null;Native 'workflow import'
  1..7|%{docker compose --env-file $envFile exec -T n8n n8n update:workflow --id="salesflow-wf-0$_" --active=true *> $null;Native "workflow 0$_ activate";docker compose --env-file $envFile exec -T n8n n8n publish:workflow --id="salesflow-wf-0$_" *> $null;Native "workflow 0$_ publish"}
  docker compose --env-file $envFile restart n8n *> $null;Native 'n8n restart'
  $ready=$false;for($i=0;$i-lt60;$i++){try{$null=Invoke-WebRequest http://127.0.0.1:5678/healthz -UseBasicParsing -TimeoutSec 2;$ready=$true;break}catch{Start-Sleep 2}};Assert $ready 'bounded published readiness'
  @'
SET search_path=salesflow,public;
SELECT set_config('sf.rt',:'rt',false);
DO $fixture$DECLARE rt text:=current_setting('sf.rt');r jsonb;r2 jsonb;i uuid;h uuid;BEGIN
  r:=ingest(rt,'{"account_ref":"test-account","provider_id":"scheduled-recovery-out","contact_ref":"scheduled-recovery-out","body":"hello"}');PERFORM set_consent(rt,'test-account',(r->>'contact_id')::uuid,'granted','schedule-fixture');r2:=complete_turn(rt,'test-account',(r->>'conversation_id')::uuid);i:=(r2->>'work_id')::uuid;r2:=claim_dispatch(rt,'test-account',i,now());UPDATE intents SET lease_until=now()-interval'1 sec'WHERE(account_ref,id)=('test-account',i);
  r:=ingest(rt,'{"account_ref":"test-account","provider_id":"scheduled-recovery-handoff","contact_ref":"scheduled-recovery-handoff","body":"human"}');r2:=complete_turn(rt,'test-account',(r->>'conversation_id')::uuid);h:=(r2->>'work_id')::uuid;r2:=claim_handoff(rt,'test-account',h,now());UPDATE handoffs SET claim_until=now()-interval'1 sec'WHERE(account_ref,id)=('test-account',h);
END$fixture$;
'@|docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -v ON_ERROR_STOP=1 -v rt=$rt *> $null;Native 'scheduled recovery fixture'
  $scheduled=$false;for($i=0;$i-lt45;$i++){$n=docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -Atc "SELECT(SELECT count(*)FROM salesflow.intents x JOIN salesflow.contact_identifiers ci ON(ci.account_ref,ci.contact_id)=(x.account_ref,x.contact_id)WHERE ci.external_ref='scheduled-recovery-out'AND ci.active AND x.state='sent')+(SELECT count(*)FROM salesflow.handoffs h JOIN salesflow.contact_identifiers ci ON(ci.account_ref,ci.contact_id)=(h.account_ref,h.contact_id)WHERE ci.external_ref='scheduled-recovery-handoff'AND ci.active AND h.state='acknowledged')";Native 'scheduled recovery poll';if($n.Trim()-eq'2'){$scheduled=$true;break};Start-Sleep 2};Assert $scheduled 'native UTC schedule recovers expired outbound and Handoff claims'
  docker compose --env-file $envFile exec -T n8n n8n export:workflow --all --separate --output=/generated/exported *> $null;Native 'workflow export'
  $source=docker compose --env-file $envFile exec -T n8n node /repo/scripts/canonicalize-workflows.mjs /repo/workflows|ConvertFrom-Json;Native 'source canonicalization'
  $export=docker compose --env-file $envFile exec -T n8n node /repo/scripts/canonicalize-workflows.mjs /generated/exported|ConvertFrom-Json;Native 'export canonicalization'
  Assert ($source.combinedSha256-eq$manifest.combinedWorkflowSha256) 'source workflow identity'
  Assert ($export.count-eq7-and$export.combinedSha256-eq$source.combinedSha256) 'imported export identity'
  $exportText=(Get-ChildItem (Join-Path $generated exported)-File|Get-Content -Raw)-join'';foreach($secret in @($rt,$rt2,$metaRuntime,$metaSecret,$metaVerify,$op,$op2,$scheduler,$super,$owner,$n8ndb,$workflowdb)){Assert (-not$exportText.Contains($secret)) 'export secret scan'}
  $rh=@{'x-salesflow-token'=$rt};$oh=@{'x-salesflow-token'=$op};$sh=@{'x-salesflow-token'=$scheduler};$base='http://127.0.0.1:5678/webhook/salesflow'
  $rej=Invoke-RestMethod "$base/inbound" -Method Post -Headers $rh -ContentType application/json -Body '{}';Assert ($rej.result.accepted-eq$false) 'ingress rejection terminal'
  $ing=Invoke-RestMethod "$base/inbound" -Method Post -Headers $rh -ContentType application/json -Body '{"account_ref":"test-account","provider_id":"live","contact_ref":"live","body":"hello"}';Assert ($ing.result.reason-eq'consent_missing') '01 to 02 fail closed'
  $cid=docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -Atc "SELECT contact_id FROM salesflow.contact_identifiers WHERE account_ref='test-account'AND channel='whatsapp'AND provider='meta'AND external_ref='live'AND active";Native 'live id';$cid=$cid.Trim()
  "SET search_path=salesflow,public;SELECT set_consent('$rt','test-account','$cid','granted','live-test');"|docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -v ON_ERROR_STOP=1 *> $null;Native 'live consent'
  $d=Invoke-RestMethod "$base/inbound" -Method Post -Headers $rh -ContentType application/json -Body '{"account_ref":"test-account","provider_id":"live-consented","contact_ref":"live","body":"hello again"}';Assert ($d.result.terminal-eq'sent') '01 to 03 automatic dispatch'
  $cbBody=@{account_ref='test-account';event_id='live-event';provider_id=$d.result.provider_id;status='delivered';provider_time=(Get-Date).ToUniversalTime().ToString('o')}|ConvertTo-Json -Compress;$cb=Invoke-RestMethod "$base/status" -Method Post -Headers $rh -ContentType application/json -Body $cbBody;Assert ($cb.status-eq'delivered') '04 live callback';Assert ((HttpStatus "$base/status" Post $rh $cbBody)-eq200) '04 duplicate callback accepted';Assert ((HttpStatus "$base/status" Post @{} $cbBody)-eq403) '04 missing token rejected';Assert ((HttpStatus "$base/status" Post $rh '{"account_ref":"test-account"}')-eq400) '04 malformed callback rejected';$missingAccount=@{event_id='live-missing-account';provider_id=$d.result.provider_id;status='sent';provider_time=(Get-Date).ToUniversalTime().ToString('o')}|ConvertTo-Json -Compress;Assert ((HttpStatus "$base/status" Post $rh $missingAccount)-eq403) '04 missing account rejected';$missingTime=@{account_ref='test-account';event_id='live-missing-time';provider_id=$d.result.provider_id;status='sent'}|ConvertTo-Json -Compress;Assert ((HttpStatus "$base/status" Post $rh $missingTime)-eq400) '04 missing provider time rejected';$missingProvider=@{account_ref='test-account';event_id='live-missing';provider_id='missing';status='sent';provider_time=(Get-Date).ToUniversalTime().ToString('o')}|ConvertTo-Json -Compress;Assert ((HttpStatus "$base/status" Post $rh $missingProvider)-eq404) '04 missing provider rejected';$conflictingCallback=@{account_ref='test-account';event_id='live-event';provider_id=$d.result.provider_id;status='read';provider_time=(Get-Date).ToUniversalTime().ToString('o')}|ConvertTo-Json -Compress;Assert ((HttpStatus "$base/status" Post $rh $conflictingCallback)-eq409) '04 conflicting callback rejected'
  $raceTime=(Get-Date).ToUniversalTime().ToString('o');$raceBody=(@{account_ref='test-account';event_id='live-race';provider_id=$d.result.provider_id;status='read';provider_time=$raceTime}|ConvertTo-Json -Compress)-replace"'","''";Race @(1..6|%{"SET search_path=salesflow,public;SELECT callback('$rt','$raceBody'::jsonb);"}) 'callback replay';$n=docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -Atc "SELECT count(*)FROM salesflow.provider_events WHERE account_ref='test-account'AND event_id='live-race'";Native 'callback race count';Assert ($n.Trim()-eq'1') 'parallel callback one event'
  @"
SET search_path=salesflow,public;
SELECT ingest('$rt',jsonb_build_object('account_ref','test-account','provider_id','live-follow','contact_ref','live-follow','body','hello'));
SELECT set_consent('$rt','test-account',contact_id,'granted','live')FROM contact_identifiers WHERE account_ref='test-account'AND channel='whatsapp'AND provider='meta'AND external_ref='live-follow'AND active;
INSERT INTO followups(account_ref,contact_id,conversation_id,due_at,expected_version)SELECT v.account_ref,v.contact_id,v.id,now()-interval'1 min',v.version FROM conversations v JOIN contact_identifiers ci ON(ci.account_ref,ci.contact_id)=(v.account_ref,v.contact_id)WHERE ci.account_ref='test-account'AND ci.channel='whatsapp'AND ci.provider='meta'AND ci.external_ref='live-follow'AND ci.active;
"@|docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -v ON_ERROR_STOP=1 *> $null;Native 'live followup fixture'
  $null=Invoke-RestMethod "$base/followups" -Method Post -Headers $sh -ContentType application/json -Body '{}'
  $n=docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -Atc "SELECT count(*) FROM salesflow.intents WHERE kind='followup'AND state='sent'";Native 'followup terminal query';Assert ([int]$n.Trim()-ge1) '05 schedules and dispatches'
  $human=Invoke-RestMethod "$base/inbound" -Method Post -Headers $rh -ContentType application/json -Body '{"account_ref":"test-account","provider_id":"live-human","contact_ref":"live-human","body":"human"}';Assert ($human.result.terminal-eq'acknowledged') '01 to 06 automatic Handoff'
  $verify=Invoke-WebRequest "$base/meta?hub.mode=subscribe&hub.verify_token=$metaVerify&hub.challenge=challenge-ok" -UseBasicParsing;Assert ($verify.StatusCode-eq200-and$verify.Content-eq'challenge-ok') 'Meta GET exact verification';Assert ((HttpStatus "$base/meta?hub.mode=subscribe&hub.verify_token=wrong&hub.challenge=no" Get @{} $null)-eq403) 'Meta GET mismatch';Assert ((HttpStatus "$base/meta?hub.mode=subscribe&hub.verify_token=$metaVerify&hub.challenge=" Get @{} $null)-eq403) 'Meta GET empty challenge rejected'
  $metaTime=[DateTimeOffset]::UtcNow.ToUnixTimeSeconds().ToString();function MetaEnvelope($items,$waba='test-waba',$phone='test-phone'){@{object='whatsapp_business_account';entry=@(@{id=$waba;changes=@(@{field='messages';value=@{metadata=@{phone_number_id=$phone};messages=$items}})})}|ConvertTo-Json -Compress -Depth 12}
  $signalBody=MetaEnvelope @(@{id='meta-human';from='meta-contact';timestamp=$metaTime;type='text';text=@{body='human'}},@{id='meta-stop';from='meta-contact';timestamp=$metaTime;type='text';text=@{body='stop'}});$metaStatus=HttpStatus "$base/meta" Post (MetaHeaders $signalBody $metaSecret) $signalBody;Assert ($metaStatus-eq200) "Meta signed batch accepted status=$metaStatus"
  $n=docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -Atc "SELECT count(*)||':'||(SELECT owner||':'||lifecycle FROM salesflow.conversations v JOIN salesflow.contact_identifiers ci ON(ci.account_ref,ci.contact_id)=(v.account_ref,v.contact_id)WHERE ci.external_ref='meta-contact'AND ci.active)||':'||(SELECT count(*)FROM salesflow.handoffs h JOIN salesflow.contact_identifiers ci ON(ci.account_ref,ci.contact_id)=(h.account_ref,h.contact_id)WHERE ci.external_ref='meta-contact'AND ci.active)||':'||(SELECT count(*)FROM salesflow.intents i JOIN salesflow.contact_identifiers ci ON(ci.account_ref,ci.contact_id)=(i.account_ref,i.contact_id)WHERE ci.external_ref='meta-contact'AND ci.active)||':'||(SELECT count(*)FROM salesflow.turns t JOIN salesflow.inbound_messages m ON(m.account_ref,m.id)=(t.account_ref,t.inbound_id)WHERE m.provider_id IN('meta-human','meta-stop')AND t.state='completed')||':'||(SELECT count(*)FROM salesflow.turns t JOIN salesflow.inbound_messages m ON(m.account_ref,m.id)=(t.account_ref,t.inbound_id)WHERE m.provider_id IN('meta-human','meta-stop')AND t.state='pending')FROM salesflow.inbound_messages WHERE provider_id IN('meta-human','meta-stop')";Native 'Meta staging query';Assert ($n.Trim()-eq'2:ai:active:0:0:2:0') 'Meta signals complete without downstream side effects'
  $order=docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -Atc "SELECT string_agg(provider_id,','ORDER BY seq)FROM salesflow.inbound_messages WHERE provider_id IN('meta-human','meta-stop')";Native 'Meta provider order query';Assert ($order.Trim()-eq'meta-human,meta-stop') 'Meta accepted batch preserves provider order'
  Assert ((HttpStatus "$base/meta" Post (MetaHeaders $signalBody $metaSecret) $signalBody)-eq200) 'Meta duplicate accepted';$invalidBody=MetaEnvelope @(@{id='meta-invalid-never';from='meta-invalid-never';timestamp=$metaTime;type='text';text=@{body='hello'}});$validSignature=(MetaHeaders $invalidBody $metaSecret)['x-hub-signature-256'];Assert ((HttpStatus "$base/meta" Post @{} $invalidBody)-eq403) 'Meta missing signature rejected';Assert ((HttpStatus "$base/meta" Post @{'x-hub-signature-256'=('sha1='+('0'*64))} $invalidBody)-eq403) 'Meta bad signature prefix rejected';Assert ((HttpStatus "$base/meta" Post @{'x-hub-signature-256'=('sha256='+('0'*63))} $invalidBody)-eq403) 'Meta short signature rejected';Assert ((HttpStatus "$base/meta" Post @{'x-hub-signature-256'=('sha256='+('0'*63)+'g')} $invalidBody)-eq403) 'Meta nonhex signature rejected';Assert ((HttpStatus "$base/meta" Post @{'x-hub-signature-256'=('sha256='+('0'*64))} $invalidBody)-eq403) 'Meta signature mismatch rejected';Assert ((HttpStatus "$base/meta" Post @{'x-hub-signature-256'="$validSignature, $validSignature"} $invalidBody)-eq403) 'Meta duplicate signature rejected';$n=docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -Atc "SELECT count(*)FROM salesflow.inbound_messages WHERE provider_id='meta-invalid-never'";Native 'Meta invalid signature persistence query';Assert ($n.Trim()-eq'0') 'Meta invalid signatures create no business persistence'
  $wrongBody=MetaEnvelope @(@{id='meta-wrong';from='meta-wrong';timestamp=$metaTime;type='text';text=@{body='hello'}}) 'wrong-waba';Assert ((HttpStatus "$base/meta" Post (MetaHeaders $wrongBody $metaSecret) $wrongBody)-eq403) 'Meta wrong identity rejected'
  $mixed=@{object='whatsapp_business_account';entry=@(@{id='test-waba';changes=@(@{field='messages';value=@{metadata=@{phone_number_id='test-phone'};messages=@(@{id='meta-mixed-valid';from='meta-mixed';timestamp=$metaTime;type='text';text=@{body='hello'}})}},@{field='messages';value=@{metadata=@{phone_number_id='wrong-phone'};messages=@(@{id='meta-mixed-wrong';from='meta-mixed';timestamp=$metaTime;type='text';text=@{body='hello'}})}})})}|ConvertTo-Json -Compress -Depth 12;Assert ((HttpStatus "$base/meta" Post (MetaHeaders $mixed $metaSecret) $mixed)-eq403) 'Meta mixed identity rejected';$n=docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -Atc "SELECT count(*)FROM salesflow.inbound_messages WHERE provider_id LIKE'meta-mixed-%'";Native 'Meta mixed identity query';Assert ($n.Trim()-eq'0') 'Meta mixed identity has no partial persistence'
  $unsupported=@{object='whatsapp_business_account';entry=@(@{id='test-waba';changes=@(@{field='messages';value=@{metadata=@{phone_number_id='test-phone'};statuses=@(@{id='status'})}})})}|ConvertTo-Json -Compress -Depth 12;Assert ((HttpStatus "$base/meta" Post (MetaHeaders $unsupported $metaSecret) $unsupported)-eq200) 'Meta unsupported event audited';$mixedSupported=@{object='whatsapp_business_account';entry=@(@{id='test-waba';changes=@(@{field='messages';value=@{metadata=@{phone_number_id='test-phone'};messages=@(@{id='meta-mixed-supported';from='meta-mixed-supported';timestamp=$metaTime;type='text';text=@{body='hello'}})}},@{field='statuses'})})}|ConvertTo-Json -Compress -Depth 12;Assert ((HttpStatus "$base/meta" Post (MetaHeaders $mixedSupported $metaSecret) $mixedSupported)-eq200) 'Meta mixed supported event accepted';$n=docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -Atc "SELECT count(*)FROM salesflow.inbound_messages WHERE provider_id='meta-mixed-supported'";Native 'Meta mixed supported query';Assert ($n.Trim()-eq'1') 'Meta mixed supported text persists once'
  $malformed='{';Assert ((HttpStatus "$base/meta" Post (MetaHeaders $malformed $metaSecret) $malformed)-eq422) 'Meta malformed JSON rejected by pinned n8n'
  $schemaInvalid=MetaEnvelope @(@{id='meta-schema-invalid';from='meta-schema-invalid';timestamp=$metaTime;type='text';text=@{}});Assert ((HttpStatus "$base/meta" Post (MetaHeaders $schemaInvalid $metaSecret) $schemaInvalid)-eq400) 'Meta schema-invalid message rejected'
  $emptyEntry=MetaEnvelope @(@{id='meta-empty-entry';from='meta-empty-entry';timestamp=$metaTime;type='text';text=@{body='hello'}}) '';Assert ((HttpStatus "$base/meta" Post (MetaHeaders $emptyEntry $metaSecret) $emptyEntry)-eq400) 'Meta empty entry id rejected';$emptyPhone=MetaEnvelope @(@{id='meta-empty-phone';from='meta-empty-phone';timestamp=$metaTime;type='text';text=@{body='hello'}}) 'test-waba' '';Assert ((HttpStatus "$base/meta" Post (MetaHeaders $emptyPhone $metaSecret) $emptyPhone)-eq400) 'Meta empty phone id rejected'
  $missingFieldObject=(MetaEnvelope @(@{id='meta-missing-field';from='meta-missing-field';timestamp=$metaTime;type='text';text=@{body='hello'}}))|ConvertFrom-Json;$missingFieldObject.entry[0].changes[0].PSObject.Properties.Remove('field');$missingField=$missingFieldObject|ConvertTo-Json -Compress -Depth 12;Assert ((HttpStatus "$base/meta" Post (MetaHeaders $missingField $metaSecret) $missingField)-eq400) 'Meta missing change field rejected'
  $largeText=MetaEnvelope @(@{id='meta-large-text';from='meta-large-text';timestamp=$metaTime;type='text';text=@{body=('é'*4097)}});Assert ((HttpStatus "$base/meta" Post (MetaHeaders $largeText $metaSecret) ([Text.Encoding]::UTF8.GetBytes($largeText)))-eq400) 'Meta text above 8192 UTF-8 bytes rejected';$future=MetaEnvelope @(@{id='meta-future';from='meta-future';timestamp=([DateTimeOffset]::UtcNow.AddMinutes(6).ToUnixTimeSeconds().ToString());type='text';text=@{body='hello'}});Assert ((HttpStatus "$base/meta" Post (MetaHeaders $future $metaSecret) $future)-eq400) 'Meta future timestamp rejected'
  $n=docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -Atc "SELECT count(*)FROM salesflow.inbound_messages WHERE provider_id IN('meta-schema-invalid','meta-empty-entry','meta-empty-phone','meta-missing-field','meta-large-text','meta-future')";Native 'Meta schema boundary persistence query';Assert ($n.Trim()-eq'0') 'Meta schema boundaries create no business persistence'
  $limitBody=MetaEnvelope @(@{id='meta-limit';from='meta-limit';timestamp=$metaTime;type='text';text=@{body='hello'}});$limitObject=$limitBody|ConvertFrom-Json;$limitObject|Add-Member padding '';do{$baseLimit=$limitObject|ConvertTo-Json -Compress -Depth 12;$need=262144-[Text.Encoding]::UTF8.GetByteCount($baseLimit);$limitObject.padding='a'*([Math]::Max(0,$limitObject.padding.Length+$need))}while($need-ne0);$limitBody=$limitObject|ConvertTo-Json -Compress -Depth 12;Assert ([Text.Encoding]::UTF8.GetByteCount($limitBody)-eq262144) 'Meta exact payload fixture';Assert ((HttpStatus "$base/meta" Post (MetaHeaders $limitBody $metaSecret) $limitBody)-eq200) 'Meta exact payload accepted';$overBody=$limitBody+' ';Assert ((HttpStatus "$base/meta" Post (MetaHeaders $overBody $metaSecret) $overBody)-eq400) 'Meta over-limit rejected';$chunkedBody=$limitBody+'  ';Assert ((ChunkedStatus "$base/meta" (MetaHeaders $chunkedBody $metaSecret) $chunkedBody)-eq400) 'Meta measured over-limit chunked body rejected'
  $conflictSeed=MetaEnvelope @(@{id='meta-conflict';from='meta-conflict';timestamp=$metaTime;type='text';text=@{body='one'}});Assert ((HttpStatus "$base/meta" Post (MetaHeaders $conflictSeed $metaSecret) $conflictSeed)-eq200) 'Meta conflict seed';$conflict=MetaEnvelope @(@{id='meta-new-rolled-back';from='meta-new';timestamp=$metaTime;type='text';text=@{body='new'}},@{id='meta-conflict';from='meta-conflict';timestamp=$metaTime;type='text';text=@{body='two'}});Assert ((HttpStatus "$base/meta" Post (MetaHeaders $conflict $metaSecret) $conflict)-eq409) 'Meta conflicting replay';$n=docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -Atc "SELECT count(*)FROM salesflow.inbound_messages WHERE provider_id='meta-new-rolled-back'";Native 'Meta rollback query';Assert ($n.Trim()-eq'0') 'Meta conflicting batch rolls back'
  $concurrent=MetaEnvelope @(@{id='meta-concurrent';from='meta-concurrent';timestamp=$metaTime;type='text';text=@{body='hello'}});$concurrentHeaders=MetaHeaders $concurrent $metaSecret;$httpJobs=@(1..6|%{Start-Job -ScriptBlock {param($uri,$headers,$body)try{[int](Invoke-WebRequest $uri -Method Post -Headers $headers -ContentType application/json -Body $body -UseBasicParsing).StatusCode}catch{if($_.Exception.Response){[int]$_.Exception.Response.StatusCode}else{throw}}} -ArgumentList "$base/meta",$concurrentHeaders,$concurrent});$httpJobs|Wait-Job|Out-Null;$statuses=@($httpJobs|Receive-Job);$httpJobs|Remove-Job;Assert (($statuses|?{$_-ne200}).Count-eq0) 'Meta concurrent retries accepted';$n=docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -Atc "SELECT count(*)FROM salesflow.inbound_messages WHERE provider_id='meta-concurrent'";Native 'Meta concurrent query';Assert ($n.Trim()-eq'1') 'Meta concurrent retry one row'
  $retiredSeed=MetaEnvelope @(@{id='meta-retired-seed';from='meta-retired-old';timestamp=$metaTime;type='text';text=@{body='hello'}});Assert ((HttpStatus "$base/meta" Post (MetaHeaders $retiredSeed $metaSecret) $retiredSeed)-eq200) 'Meta retired-reference seed accepted';$retiredContact=docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -Atc "SELECT contact_id FROM salesflow.contact_identifiers WHERE account_ref='test-account'AND external_ref='meta-retired-old'AND active";Native 'Meta retired-reference Contact query';$retiredContact=$retiredContact.Trim();$replaced=Invoke-RestMethod "$base/operations" -Method Post -Headers $oh -ContentType application/json -Body (@{action='contact_identifier_replace';contact_id=$retiredContact;channel='whatsapp';provider='meta';old_ref='meta-retired-old';new_ref='meta-retired-new'}|ConvertTo-Json -Compress);Assert ($replaced.created) '07 identifier replacement accepted';$retiredDelivery=MetaEnvelope @(@{id='meta-retired-late';from='meta-retired-old';timestamp=$metaTime;type='text';text=@{body='late'}});Assert ((HttpStatus "$base/meta" Post (MetaHeaders $retiredDelivery $metaSecret) $retiredDelivery)-eq410) 'Meta retired reference is terminal and non-retryable';$conflictOwner=MetaEnvelope @(@{id='meta-identifier-conflict-owner';from='meta-identifier-conflict-owner';timestamp=$metaTime;type='text';text=@{body='hello'}});Assert ((HttpStatus "$base/meta" Post (MetaHeaders $conflictOwner $metaSecret) $conflictOwner)-eq200) 'Meta identifier conflict owner seed';Assert ((HttpStatus "$base/operations" Post $oh (@{action='contact_identifier_replace';contact_id=$retiredContact;channel='whatsapp';provider='meta';old_ref='meta-retired-new';new_ref='meta-identifier-conflict-owner'}|ConvertTo-Json -Compress))-eq409) '07 identifier ownership conflict maps to HTTP 409'
  $audit=docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -Atc "WITH e AS(SELECT reason,details,count(*) n FROM salesflow.audit_events WHERE event='ingress_rejected'GROUP BY reason,details)SELECT sum(n)||':'||string_agg(DISTINCT reason,','ORDER BY reason)||':'||bool_and(details ? 'correlation'AND details=jsonb_build_object('correlation',details->'correlation'))||':'||bool_and(n=1)FROM e";Native 'Meta rejection audit query';$auditParts=$audit.Trim()-split':';Assert ([int]$auditParts[0]-eq14-and$auditParts[1]-eq'idempotency_conflict,identifier_retired,invalid_signature,malformed_payload,oversized_payload,unsupported_event,wrong_identity'-and$auditParts[2]-eq'true'-and$auditParts[3]-eq'true') 'Meta rejection audit exact, unique, and minimized'
  "SET search_path=salesflow,public;REVOKE EXECUTE ON FUNCTION record_ingress_rejection(text,text,text)FROM salesflow_runtime;"|docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -v ON_ERROR_STOP=1 *> $null;Native 'Meta rejection failure fixture';$rejectionFail=HttpStatus "$base/meta" Post @{'x-hub-signature-256'=('sha256='+('0'*64))} $invalidBody;"SET search_path=salesflow,public;GRANT EXECUTE ON FUNCTION record_ingress_rejection(text,text,text)TO salesflow_runtime;"|docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -v ON_ERROR_STOP=1 *> $null;Native 'Meta rejection failure restore';Assert ($rejectionFail-eq500) 'Meta rejection database failure returns 5xx'
  "SET search_path=salesflow,public;REVOKE EXECUTE ON FUNCTION ingest_meta(text,jsonb)FROM salesflow_runtime;"|docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -v ON_ERROR_STOP=1 *> $null;Native 'Meta failure fixture';$dbFail=HttpStatus "$base/meta" Post (MetaHeaders $signalBody $metaSecret) $signalBody;"SET search_path=salesflow,public;GRANT EXECUTE ON FUNCTION ingest_meta(text,jsonb)TO salesflow_runtime;"|docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -v ON_ERROR_STOP=1 *> $null;Native 'Meta failure restore';Assert ($dbFail-eq500) 'Meta database failure returns 5xx'
  $ops=Invoke-RestMethod "$base/operations" -Method Post -Headers $oh -ContentType application/json -Body '{"action":"evidence"}';Assert ($ops.account_ref-eq'test-account') '07 account evidence';$httpDoc=@{accountRef='test-account';kind='qualification';version='qualification-http';minimumScore=1;handoffScore=5};$saved=Invoke-RestMethod "$base/operations" -Method Post -Headers $oh -ContentType application/json -Body (@{action='config_save';document=$httpDoc}|ConvertTo-Json -Compress -Depth 5);Assert ($saved.created) '07 config save';$activated=Invoke-RestMethod "$base/operations" -Method Post -Headers $oh -ContentType application/json -Body (@{action='config_activate';kind='qualification';version='qualification-http';expected_active_version='qualification-v1'}|ConvertTo-Json -Compress);Assert ($activated.activated) '07 config activate';$rolledBack=Invoke-RestMethod "$base/operations" -Method Post -Headers $oh -ContentType application/json -Body (@{action='config_rollback';kind='qualification';version='qualification-v1';expected_active_version='qualification-http'}|ConvertTo-Json -Compress);Assert ($rolledBack.activated) '07 config rollback';$crossDoc=@{accountRef='account-b';kind='qualification';version='qualification-cross';minimumScore=1;handoffScore=5};Assert ((HttpStatus "$base/operations" Post $oh (@{action='config_save';document=$crossDoc}|ConvertTo-Json -Compress -Depth 5))-eq403) '07 cross-account config denied';$badDoc=@{accountRef='test-account';kind='qualification';version='qualification-bad-http';minimumScore=1.5;handoffScore=5};Assert ((HttpStatus "$base/operations" Post $oh (@{action='config_save';document=$badDoc}|ConvertTo-Json -Compress -Depth 5))-eq400) '07 invalid config rejected';@'
SET search_path=salesflow,public;
CREATE OR REPLACE FUNCTION fail_config_audit_fixture()RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF NEW.event='config_saved'THEN RAISE EXCEPTION 'fixture failure';END IF;RETURN NEW;END$$;
CREATE TRIGGER fail_config_audit_fixture BEFORE INSERT ON audit_events FOR EACH ROW EXECUTE FUNCTION fail_config_audit_fixture();
'@|docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -v ON_ERROR_STOP=1 *> $null;Native 'operations failure fixture';$failureDoc=@{accountRef='test-account';kind='qualification';version='qualification-failure-http';minimumScore=1;handoffScore=5};$operationsFail=HttpStatus "$base/operations" Post $oh (@{action='config_save';document=$failureDoc}|ConvertTo-Json -Compress -Depth 5);"SET search_path=salesflow,public;DROP TRIGGER fail_config_audit_fixture ON audit_events;DROP FUNCTION fail_config_audit_fixture();"|docker compose --env-file $envFile exec -T postgres psql -U postgres -d salesflow -v ON_ERROR_STOP=1 *> $null;Native 'operations failure restore';Assert ($operationsFail-eq500) "07 internal database failure returns 5xx status=$operationsFail"
  Pass 'FULL PASS'
}catch{$failure=$_}
finally{
  $preserveLocal=$KeepRunning-and-not$failure
  if($managedEnvironment){
    if($preserveLocal){
      try{Copy-Item $envFile $localEnvFile -Force}catch{$cleanupFailure='local .env persistence failed'}
      if(-not$cleanupFailure){
        Get-ChildItem $generated -Force|Remove-Item -Recurse -Force
        if(@(Get-ChildItem $generated -Force).Count){$cleanupFailure='plaintext generated files remain'}
        $running=@(docker compose --env-file $localEnvFile ps --status running -q)
        $postgresId=docker compose --env-file $localEnvFile ps -q postgres
        $postgresHealth=if($LASTEXITCODE-eq0-and$postgresId){docker inspect --format '{{.State.Health.Status}}' $postgresId}else{''}
        try{$n8nHealth=(Invoke-RestMethod http://127.0.0.1:5678/healthz -TimeoutSec 5).status}catch{$n8nHealth=''}
        if($LASTEXITCODE-ne0-or$running.Count-ne2-or$postgresHealth-ne'healthy'-or$n8nHealth-ne'ok'){$cleanupFailure='local stack not healthy'}
      }
    }else{
      if(Test-Path $envFile){docker compose --env-file $envFile down -v --remove-orphans *> $null;if($LASTEXITCODE-ne0){$cleanupFailure='compose cleanup failed; recovery credentials retained in .generated/runtime.env'}}
      if(-not$cleanupFailure){
        Remove-Item $generated -Recurse -Force -ErrorAction SilentlyContinue
        if(Test-Path $generated){$cleanupFailure='plaintext generated directory remains'}
        $remaining=@(docker volume ls --filter "label=com.docker.compose.project=$composeProject" -q)
        if($LASTEXITCODE-ne0-or$remaining){$cleanupFailure='project volumes remain'}
      }
    }
  }
  if($lockAcquired){$mutex.ReleaseMutex()};$mutex.Dispose()
}
if($cleanupFailure){throw $cleanupFailure}
if($failure){throw $failure}
Pass 'plaintext generated credentials removed'
if($KeepRunning){Pass 'local stack running at http://127.0.0.1:5678';Pass 'ignored local .env retained'}else{Pass 'container volumes removed'}
