SET search_path=salesflow,public;
DO $$DECLARE r jsonb;BEGIN
 r:=operations('sp3t6-operator',NULL,'{"action":"emergency_stop","enabled":true}');
 IF NOT COALESCE((r->>'ok')::bool,false)OR r->>'terminal'<>'emergency_stop'OR r->>'enabled'<>'true'THEN RAISE EXCEPTION'emergency stop was not accepted: %',r;END IF;
 IF NOT EXISTS(SELECT 1 FROM audit_events WHERE account_ref='sp3t6'AND event='emergency_stop_changed'AND actor='sp3t6-operator'AND details->>'previousEnabled'='false'AND details->>'enabled'='true')THEN RAISE EXCEPTION'emergency stop attribution missing';END IF;
 r:=operations('sp3t6-operator',NULL,'{"action":"activity","limit":1}');
 IF NOT COALESCE((r->>'ok')::bool,false)OR jsonb_array_length(r->'items')<>1 OR r->'items'->0->>'actor'<>'sp3t6-operator'THEN RAISE EXCEPTION'activity view invalid: %',r;END IF;
 r:=operations('sp3t6-other-operator',NULL,'{"action":"activity","limit":100}');
 IF r::text LIKE'%sp3t6-operator%'THEN RAISE EXCEPTION'activity leaked across accounts';END IF;
 IF (operations('sp3t6-operator',NULL,'{"action":"activity","limit":0}')->>'reason')<>'invalid_input'OR(operations('sp3t6-operator',NULL,'{"action":"activity","limit":101}')->>'reason')<>'invalid_input'OR(operations('sp3t6-operator',NULL,'{"action":"activity","limit":2147483648}')->>'reason')<>'invalid_input'OR(operations('sp3t6-operator',NULL,'{"action":"activity","cursor":9223372036854775808}')->>'reason')<>'invalid_input'OR(operations('sp3t6-operator',NULL,'{"action":"activity","limit":null}')->>'reason')<>'invalid_input'THEN RAISE EXCEPTION'activity bounds accepted';END IF;
 IF (operations('sp3t6-operator',NULL,'{"action":"failures","limit":2147483648}')->>'reason')<>'invalid_input'OR(operations('sp3t6-operator',NULL,'{"action":"failures","cursor":9223372036854775808}')->>'reason')<>'invalid_input'THEN RAISE EXCEPTION'failure bounds accepted';END IF;
 r:=operations('sp3t6-operator',NULL,'{"action":"activity","limit":100}');IF NOT EXISTS(SELECT 1 FROM jsonb_array_elements(r->'items')x WHERE x->>'action'='config_activated'AND x->>'entityType'='config'AND COALESCE(x->>'entityId','')<>'')THEN RAISE EXCEPTION'config activity identity missing: %',r;END IF;
 IF (operations('sp3t6-runtime',NULL,'{"action":"failures"}')->>'reason')<>'wrong_account'THEN RAISE EXCEPTION'runtime read did not fail closed';END IF;
 r:=operations('sp3t6-operator',NULL,'{"action":"emergency_stop","enabled":false}');
 IF NOT COALESCE((r->>'ok')::bool,false)OR r->>'enabled'<>'false'THEN RAISE EXCEPTION'emergency resume was not accepted: %',r;END IF;
END$$;

WITH c AS(INSERT INTO contacts(account_ref)VALUES('sp3t6')RETURNING id),v AS(INSERT INTO conversations(account_ref,contact_id)SELECT'sp3t6',id FROM c RETURNING id,contact_id),m AS(INSERT INTO inbound_messages(account_ref,conversation_id,provider_id,contact_ref,body,processing_body,body_hash,received_at,seq)SELECT'sp3t6',id,'sp3t6-failure','fixture','fixture','fixture',encode(digest('fixture','sha256'),'hex'),clock_timestamp(),1 FROM v RETURNING id,conversation_id),i AS(INSERT INTO intents(account_ref,contact_id,conversation_id,source_id,kind,expected_version,policy_version,knowledge_version,body,provenance,state,reason,attempts,next_attempt)SELECT'sp3t6',v.contact_id,v.id,m.id,'reply',0,'unknown','unknown','synthetic','{}','retry','pre_call_retryable',2,clock_timestamp()+interval'1 minute'FROM v,m RETURNING id)INSERT INTO intent_transitions(account_ref,intent_id,from_state,to_state,reason)SELECT'sp3t6',id,'leased','pending','pre_call_retryable'FROM i;
DO $$DECLARE r jsonb;BEGIN
 r:=operations('sp3t6-operator',NULL,'{"action":"failures","limit":50}');
 IF NOT COALESCE((r->>'ok')::bool,false)OR NOT EXISTS(SELECT 1 FROM jsonb_array_elements(r->'items')x WHERE x->>'workType'='message'AND x->>'state'='pending'AND x->>'attempt'= '2'AND x->>'nextRetry'IS NOT NULL AND x->>'manualActionRequired'='false')THEN RAISE EXCEPTION'failure visibility invalid: %',r;END IF;
 IF r::text LIKE'%synthetic%'THEN RAISE EXCEPTION'failure view exposed message body';END IF;
END$$;
DO $$DECLARE work uuid;r jsonb;BEGIN SELECT id INTO work FROM intents WHERE account_ref='sp3t6'AND reason='pre_call_retryable'ORDER BY id LIMIT 1;INSERT INTO intent_transitions(account_ref,intent_id,from_state,to_state,reason)VALUES('sp3t6',work,'provider_call_started','failed','provider_call_failed');r:=operations('sp3t6-operator',NULL,'{"action":"failures","limit":100}');IF NOT EXISTS(SELECT 1 FROM jsonb_array_elements(r->'items')x WHERE x->>'workId'=work::text AND x->>'state'='failed'AND x->>'latestReason'='provider_call_failed'AND x->>'manualActionRequired'='true')THEN RAISE EXCEPTION'terminal transition truth missing: %',r;END IF;INSERT INTO intent_transitions(account_ref,intent_id,from_state,to_state,reason)VALUES('sp3t6',work,'leased','suppressed','retry_exhausted');r:=operations('sp3t6-operator',NULL,'{"action":"failures","limit":100}');IF NOT EXISTS(SELECT 1 FROM jsonb_array_elements(r->'items')x WHERE x->>'workId'=work::text AND x->>'state'='suppressed'AND x->>'latestReason'='retry_exhausted')THEN RAISE EXCEPTION'exhaustion visibility missing: %',r;END IF;IF NOT EXISTS(SELECT 1 FROM pg_indexes WHERE schemaname='salesflow'AND indexname='audit_events_account_id_desc')OR NOT EXISTS(SELECT 1 FROM pg_indexes WHERE schemaname='salesflow'AND indexname='operational_failures_account_id_desc')THEN RAISE EXCEPTION'account keyset indexes missing';END IF;END$$;
SELECT 'PASS SP3-T6 SQL';
