param()
$ErrorActionPreference='Stop'
$root=Split-Path -Parent $PSScriptRoot
$container='salesflow-sp3t5-'+[guid]::NewGuid().ToString('N')
$launched=$false;$jobs=@()
function Query([string]$sql){$prior=$ErrorActionPreference;$ErrorActionPreference='Continue';$output=@($sql|docker exec -i -e PGOPTIONS=-cclient_min_messages=error $container psql -U postgres -v ON_ERROR_STOP=1 -v VERBOSITY=verbose -qAt 2>&1|ForEach-Object{$_.ToString()});$code=$LASTEXITCODE;$ErrorActionPreference=$prior;if($code-ne0){throw "SP3-T5 SQL failed: $($output -join [Environment]::NewLine)"};$output}
function Check($condition,[string]$label){if(-not$condition){throw "SP3-T5 $label"};Write-Host "PASS SP3-T5 $label"}
try{
 $manifest=Get-Content (Join-Path $root 'release/release-manifest.json') -Raw|ConvertFrom-Json
 $image=[string]$manifest.images[0];Check ($image-match'^postgres@sha256:[a-f0-9]{64}$') 'pinned PostgreSQL image'
 $password=[guid]::NewGuid().ToString('N')
 docker run --detach --rm --name $container --network none -e "POSTGRES_PASSWORD=$password" $image *> $null;Check ($LASTEXITCODE-eq0) 'disposable PostgreSQL started';$launched=$true
 $ready=$false;for($n=0;$n-lt60;$n++){docker exec $container pg_isready -U postgres *> $null;if($LASTEXITCODE-eq0){$ready=$true;break};Start-Sleep -Milliseconds 250};Check $ready 'database ready'
 $migration=Get-Content (Join-Path $root 'database/001-initial.sql') -Raw;$encoded=[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($password));foreach($placeholder in @('__MIGRATION_PASSWORD_B64__','__WORKFLOW_DB_PASSWORD_B64__','__N8N_DB_PASSWORD_B64__')){$migration=$migration.Replace($placeholder,$encoded)}
 Query $migration|Out-Null;Write-Host 'PASS SP3-T5 migration 1'
 Query "SET search_path=salesflow,public;INSERT INTO accounts VALUES('sp3t5',true),('other',true);INSERT INTO controls VALUES('sp3t5','stop','{`"enabled`":false}'),('other','stop','{`"enabled`":false}');SELECT bootstrap('sp3t5-runtime','runtime','sp3t5','sp3t5');SELECT bootstrap('sp3t5-operator','operator','sp3t5','sp3t5');SELECT bootstrap('sp3t5-other-operator','operator','other','other');SELECT bootstrap('sp3t5-other-runtime','runtime','other','other');SELECT bootstrap('sp3t5-other-scheduler','scheduler','other','other');SELECT bootstrap('sp3t5-unscoped-runtime','runtime','global-runtime',NULL);"|Out-Null
 foreach($file in Get-ChildItem (Join-Path $root 'config') -Filter *.json|Where-Object Name -ne 'account.json'){$doc=Get-Content $file.FullName -Raw|ConvertFrom-Json;$doc.accountRef='sp3t5';$json=($doc|ConvertTo-Json -Compress -Depth 30).Replace("'","''");$r=Query "SELECT salesflow.save_config('sp3t5-operator','$json');"|ConvertFrom-Json;Check $r.created "save $($file.Name)";$r=Query "SELECT salesflow.activate_config('sp3t5-operator','sp3t5','$($doc.kind)','$($doc.version)',NULL);"|ConvertFrom-Json;Check $r.activated "activate $($file.Name)"}
 Query (Get-Content (Join-Path $PSScriptRoot 'sp3-t5.sql') -Raw)|ForEach-Object{Write-Host $_}
 Query "SET search_path=salesflow,public;WITH c AS(INSERT INTO contacts(account_ref)VALUES('sp3t5')RETURNING id),v AS(INSERT INTO conversations(account_ref,contact_id,owner)SELECT'sp3t5',id,'human'FROM c RETURNING id,contact_id),m AS(INSERT INTO inbound_messages(account_ref,conversation_id,provider_id,contact_ref,body,processing_body,body_hash,received_at,seq)SELECT'sp3t5',id,'legacy-summary','legacy','legacy','legacy',encode(digest('legacy','sha256'),'hex'),now(),0 FROM v RETURNING id,conversation_id),h AS(INSERT INTO handoffs(account_ref,contact_id,conversation_id,source_id,reason,queue,deadline,evidence,state,claim,claim_until,attempts)SELECT'sp3t5',v.contact_id,v.id,m.id,'human_requested','synthetic-sales',now()+interval'5 min','{}','claimed','11111111-1111-4111-8111-111111111111',now()-interval'1 minute',1 FROM v,m RETURNING id)SELECT id FROM h;"|Out-Null
 Query $migration|Out-Null;Write-Host 'PASS SP3-T5 migration 2';Query $migration|Out-Null;Write-Host 'PASS SP3-T5 migration 3'
 $legacy=Query "SET search_path=salesflow,public;SELECT count(*)||':'||min(sales_policy_version)||':'||min(relevant_offer)FROM handoff_summaries s JOIN inbound_messages m ON(m.account_ref,m.id)=(s.account_ref,s.source_id)WHERE m.provider_id='legacy-summary';";Check ($legacy.Trim()-eq'1:unknown:none') 'legacy conservative backfill once'
 $legacyAttempt=Query "SET search_path=salesflow,public;SELECT count(*)||':'||bool_and(a.started_at IS NULL)||':'||(SELECT claim_handoff('sp3t5-runtime','sp3t5',h.id,clock_timestamp())->>'reason')||':'||(SELECT finish_handoff('sp3t5-runtime','sp3t5',h.id,h.claim,'success')->>'reason')FROM handoffs h JOIN inbound_messages m ON(m.account_ref,m.id)=(h.account_ref,h.source_id)JOIN handoff_notification_attempts a ON(a.account_ref,a.handoff_id,a.attempt_no,a.claim)=(h.account_ref,h.id,h.attempts,h.claim)WHERE m.provider_id='legacy-summary'GROUP BY h.id,h.claim;";Check ($legacyAttempt.Trim()-eq'1:true:reconciliation_required:reconciliation_required') 'legacy claimed handoff conservatively blocks blind reclaim without inventing adapter start'
 $workflow=Get-Content (Join-Path $root 'workflows/06-handoff-dispatcher.json') -Raw|ConvertFrom-Json
 Check (@($workflow.nodes|Where-Object{$_.name-eq'Authenticated Conversation History'}).Count-eq1) 'Workflow 06 authenticated history route'
 $historyNode=$workflow.nodes|Where-Object{$_.name-eq'Authenticated Conversation History'}
 Check ($historyNode.parameters.query-match'read_conversation_history_request\(\$1,\$2\)'-and$historyNode.parameters.options.queryReplacement-notmatch'account_ref') 'history account scope derives from operator token'
 Check ((Get-Content (Join-Path $root 'workflows/06-handoff-dispatcher.json') -Raw)-notmatch'operator.*token.*conversation_url') 'conversation URL excludes credentials'
 $worker={param($name)$sql="SET search_path=salesflow,public;SELECT salesflow.ingest('sp3t5-runtime','{`"account_ref`":`"sp3t5`",`"provider_id`":`"summary-race`",`"contact_ref`":`"summary-race`",`"body`":`"talk to a human`"}');";$out=$sql|docker exec -i -e PGOPTIONS=-cclient_min_messages=error $name psql -U postgres -v ON_ERROR_STOP=1 -qAt 2>&1;if($LASTEXITCODE-ne0){throw $out};$out}
 $jobs=@(1..2|ForEach-Object{Start-Job -ScriptBlock $worker -ArgumentList $container});$done=@($jobs|Wait-Job -Timeout 20);Check ($done.Count-eq2-and@($jobs|Where-Object State -ne 'Completed').Count-eq0) 'concurrent summary requests completed';$jobs|Receive-Job|Out-Null
 $race=Query "SET search_path=salesflow,public;SELECT count(*)||':'||(SELECT count(*)FROM handoff_summaries s JOIN handoffs h ON(h.account_ref,h.id)=(s.account_ref,s.handoff_id)JOIN inbound_messages m ON(m.account_ref,m.id)=(h.account_ref,h.source_id)WHERE m.provider_id='summary-race')FROM handoffs h JOIN inbound_messages m ON(m.account_ref,m.id)=(h.account_ref,h.source_id)WHERE m.provider_id='summary-race';"
 Check ($race.Trim()-eq'1:1') 'concurrent replay creates one handoff and one summary'
 $claimRace=Query "SET search_path=salesflow,public;SELECT claim_handoff('sp3t5-runtime','sp3t5',(SELECT h.id FROM handoffs h JOIN inbound_messages m ON(m.account_ref,m.id)=(h.account_ref,h.source_id)WHERE m.provider_id='summary-race'),clock_timestamp());"|ConvertFrom-Json
 Check $claimRace.ok 'concurrent recheck fixture claimed'
 $recheckWorker={param($name,$work,$claim)$sql="SELECT salesflow.recheck_handoff('sp3t5-runtime','sp3t5','$work','$claim');";$out=$sql|docker exec -i -e PGOPTIONS=-cclient_min_messages=error $name psql -U postgres -v ON_ERROR_STOP=1 -qAt 2>&1;if($LASTEXITCODE-ne0){throw $out};$out}
 $jobs|Remove-Job -Force;$jobs=@(1..2|ForEach-Object{Start-Job -ScriptBlock $recheckWorker -ArgumentList $container,$claimRace.work_id,$claimRace.claim})
 $done=@($jobs|Wait-Job -Timeout 20);Check ($done.Count-eq2-and@($jobs|Where-Object State -ne 'Completed').Count-eq0) 'concurrent adapter rechecks completed'
 $results=@($jobs|Receive-Job|ForEach-Object{$_|ConvertFrom-Json});Check (@($results|Where-Object ok).Count-eq1-and@($results|Where-Object reason -eq 'adapter_already_started').Count-eq1) 'concurrent rechecks authorize adapter exactly once'
 Write-Host 'PASS SP3-T5 FULL PASS'
}finally{foreach($job in $jobs){if($job.State-eq'Running'){$job|Stop-Job};$job|Remove-Job -Force -ErrorAction SilentlyContinue};if($launched){docker rm --force --volumes $container *> $null;Check ($LASTEXITCODE-eq0) 'disposable container and volumes removed'}}
